# Generated by Django 2.2.5 on 2022-07-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220630_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bedroom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.IntegerField(null=True),
        ),
    ]
