# Generated by Django 2.2.5 on 2022-07-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20220701_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='contry',
            new_name='country',
        ),
    ]
