# Generated by Django 2.2.5 on 2022-06-30 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20220630_1825'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lists',
            new_name='List',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='namd',
            new_name='name',
        ),
    ]
